version: 2
updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ¤–dependencies"
    open-pull-requests-limit: 0
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ¤–dependencies"
      - "ğŸ™actions"
